### PR TITLE
Fix UI resetting person list after every command

### LINKED ISSUE #227: Fix UI resetting person list after every command
When a command is run, the person list is always reset. This affects the matchPerson command tag highlighting in the UI which in turn gives the wrong behaviour.

### PR DESCRIPTION
**Pull request by Ryuse**
Fixes #227

Before
image

after `searchPerson t/test`
image

### CODE REVIEW

File: src/main/java/seedu/address/model/ModelManager.java [hunk 1]
```diff
@@ -243,21 +239,70 @@ public ObservableList<Tag> getFilteredTagList() {
...
+        if (comparator.equals(sortedFilteredListings.getComparator())) {
+            sortedFilteredListings.setComparator(COMPARATOR_SHOW_ALL_LISTINGS);
+        }
+
         sortedFilteredListings.setComparator(comparator);
     }
 
     @Override
     public void updateFilteredTagList(Predicate<Tag> predicate) {
         requireNonNull(predicate);
```
Comment (ToxOptimism) [inline src/main/java/seedu/address/model/ModelManager.java:301]: Perhaps this can be updated with a null if condition to standardize with other updateFiltered__List?

File: src/main/java/seedu/address/model/person/PropertyPreference.java [hunk 2]
```diff
@@ -68,16 +68,17 @@ public void removeTag(Tag toDelete) {
     }
 
     /**
-     * Checks whether this {@code PropertyPreference} matches all the given search tags.
+     * Checks whether this {@code PropertyPreference} is to be shown in the UI.
```
Comment (ToxOptimism) [inline src/main/java/seedu/address/model/person/PropertyPreference.java:71]: Perhaps this JavaDoc can be written such that it does not imply it is dependent on the UI component?

For example: "Checks whether this {@code PropertyPreference} contains at least one of the tags specified by the active search tags.

File: src/main/java/seedu/address/model/person/PropertyPreference.java [hunk 3]
```diff
@@ -68,16 +68,17 @@ public void removeTag(Tag toDelete) {
...
      * @return True if preference contains all the specified search tags (case-insensitive), or if searchTags is empty.
      */
-    public boolean matchesSearchTags(Set<String> searchTags) {
-        return searchTags.isEmpty()
-                || searchTags.stream()
-                .allMatch(tagName -> tags.stream()
-                        .anyMatch(tag -> tag.tagName.equalsIgnoreCase(tagName)));
+    public boolean isActive() {
+
+        boolean tagMatches = tags.stream().anyMatch(tag -> Tag
```
Comment (ToxOptimism) [inline src/main/java/seedu/address/model/person/PropertyPreference.java:77]: I believe this does not match the JavaDoc, which specifies that the preference should contain all the specified search tags? 

However, I believe this might be linked to a bigger issue as it appears this function is intended to be used by both search command and match command. Search which requires all, and Match that requires any.

File: src/main/java/seedu/address/model/person/PropertyPreference.java [hunk 4]
```diff
@@ -68,16 +68,17 @@ public void removeTag(Tag toDelete) {
...
+                .getActiveSearchTags()
+                .containsKey(tag.tagName));
+
+        return tagMatches || Tag.getActiveSearchTags().isEmpty();
```
Comment (ToxOptimism) [inline src/main/java/seedu/address/model/person/PropertyPreference.java:81]: Perhaps an early return could be used for the latter clause?

File: src/main/java/seedu/address/model/ModelManager.java [hunk 5]
```diff
@@ -150,8 +156,8 @@ public void deleteTag(Tag target) {
     @Override
     public void addPerson(Person person) {
```
Comment (ToxOptimism) [inline src/main/java/seedu/address/model/ModelManager.java:157]: I believe this code change is missing from setPerson?

**Review by ToxOptimism — CHANGES_REQUESTED** [review]
There seems to be a couple issues with the code. Do check if the (search) commands still work with multiple tags specified.

File: src/main/java/seedu/address/model/person/predicates/PropertyPreferencesContainAllActiveSearchTagsPredicate.java [hunk 6]
```diff
@@ -0,0 +1,26 @@
...
+/**
+ * Tests that a {@code Person}'s property preferences contain all the specified tags.
+ */
+public class PropertyPreferencesContainAllActiveSearchTagsPredicate implements Predicate<PropertyPreference> {
+
+    @Override
+    public boolean test(PropertyPreference preference) {
+        Set<Tag> tagsToMatch = new HashSet<>(Tag.getActiveSearchTags().values());
+        Set<Tag> preferenceTags = preference.getTags();
+        return preferenceTags.containsAll(tagsToMatch) && preferenceTags.size() == tagsToMatch.size();
```
Comment (ToxOptimism) [inline src/main/java/seedu/address/model/person/predicates/PropertyPreferencesContainAllActiveSearchTagsPredicate.java:19]: I believe the size check is not needed, as the preferenceTags size can be greater than tags required to match?

For example, if a preference has 5 tags and the filter only has 3, all of which are included in the preference. It should still show the preference.

File: src/main/java/seedu/address/model/person/predicates/PropertyPreferencesContainAllActiveSearchTagsPredicate.java [hunk 7]
```diff
@@ -0,0 +1,26 @@
...
+import seedu.address.model.tag.Tag;
+
+/**
+ * Tests that a {@code Person}'s property preferences contain all the specified tags.
+ */
+public class PropertyPreferencesContainAllActiveSearchTagsPredicate implements Predicate<PropertyPreference> {
+
+    @Override
+    public boolean test(PropertyPreference preference) {
+        Set<Tag> tagsToMatch = new HashSet<>(Tag.getActiveSearchTags().values());
```
Comment (ToxOptimism) [inline src/main/java/seedu/address/model/person/predicates/PropertyPreferencesContainAllActiveSearchTagsPredicate.java:17]: Perhaps an early return check for if the tagsToMatch is empty can be included here?

File: src/main/java/seedu/address/model/person/predicates/PropertyPreferencesContainAnyActiveSearchTagsPredicate.java [hunk 8]
```diff
@@ -0,0 +1,27 @@
...
+import seedu.address.model.tag.Tag;
+
+/**
+ * Tests that a {@code Person}'s property preferences contain all the specified tags.
+ */
+public class PropertyPreferencesContainAnyActiveSearchTagsPredicate implements Predicate<PropertyPreference> {
+
+    @Override
+    public boolean test(PropertyPreference preference) {
+        Set<Tag> tagsToMatch = new HashSet<>(Tag.getActiveSearchTags().values());
```
Comment (ToxOptimism) [inline src/main/java/seedu/address/model/person/predicates/PropertyPreferencesContainAnyActiveSearchTagsPredicate.java:18]: Perhaps an early return check for if the tagsToMatch is empty can be included here?

File: src/main/java/seedu/address/model/person/predicates/PropertyPreferencesContainAnyActiveSearchTagsPredicate.java [hunk 9]
```diff
@@ -0,0 +1,27 @@
...
+        Set<Tag> preferenceTags = preference.getTags();
+        return !Collections.disjoint(preferenceTags, tagsToMatch);
```
Comment (ToxOptimism) [inline src/main/java/seedu/address/model/person/predicates/PropertyPreferencesContainAnyActiveSearchTagsPredicate.java:20]: I believe this section of the code produces a bugged result as:
When tagsToMatch is empty, !Collections.disjoint() will return false no matter what, therefore hiding all matched preferences. 

The earlier suggestion for adding a early return null check could help.

File: src/main/java/seedu/address/model/person/predicates/PropertyPreferencesContainAllActiveSearchTagsPredicate.java [hunk 10]
```diff
@@ -0,0 +1,26 @@
+package seedu.address.model.person.predicates;
```
Comment (ToxOptimism) [inline src/main/java/seedu/address/model/person/predicates/PropertyPreferencesContainAllActiveSearchTagsPredicate.java:1]: Nice use of predicate classes abstracting complex filtering from the commands!

**Review by ToxOptimism — CHANGES_REQUESTED** [review]
Code looks fairly good, however there are a couple issues that should be looked at before merging.

File: src/main/java/seedu/address/model/person/predicates/PropertyPreferencesContainAllActiveSearchTagsPredicate.java (hunk 10 above)
Comment (Ryuse) [reply src/main/java/seedu/address/model/person/predicates/PropertyPreferencesContainAllActiveSearchTagsPredicate.java:1]: Thanks!

File: src/main/java/seedu/address/model/person/predicates/PropertyPreferencesContainAnyActiveSearchTagsPredicate.java (hunk 9 above)
Comment (Ryuse) [reply src/main/java/seedu/address/model/person/predicates/PropertyPreferencesContainAnyActiveSearchTagsPredicate.java:25]: True. I'll make the changes!

File: src/main/java/seedu/address/model/person/predicates/PropertyPreferencesContainAllActiveSearchTagsPredicate.java (hunk 7 above)
Comment (Ryuse) [reply src/main/java/seedu/address/model/person/predicates/PropertyPreferencesContainAllActiveSearchTagsPredicate.java:17]: Alright!

File: src/main/java/seedu/address/model/person/predicates/PropertyPreferencesContainAnyActiveSearchTagsPredicate.java (hunk 8 above)
Comment (Ryuse) [reply src/main/java/seedu/address/model/person/predicates/PropertyPreferencesContainAnyActiveSearchTagsPredicate.java:18]: Alright!

File: src/main/java/seedu/address/model/ModelManager.java (hunk 5 above)
Comment (Ryuse) [reply src/main/java/seedu/address/model/ModelManager.java:157]: True. I'll put it in.

File: src/main/java/seedu/address/model/person/predicates/PropertyPreferencesContainAllActiveSearchTagsPredicate.java (hunk 6 above)
Comment (Ryuse) [reply src/main/java/seedu/address/model/person/predicates/PropertyPreferencesContainAllActiveSearchTagsPredicate.java]: I see, so it's not an exact match. I'll remove the size check.

**Review by ToxOptimism — APPROVED** [review]
LGTM! All changes requested have been accounted for.

**Review by lesterlimjj — APPROVED** [review]
I have tested with Lemuel on the intended behavior of all commands and resolved any found bugs during it.
